# Generated by Django 5.1.4 on 2026-07-02 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('SCHOOL', 'School (exam prep)'), ('COMPANY', 'Company (interview prep)'), ('INSTITUTE', 'Coaching institute (interview prep)'), ('INDIVIDUAL', 'Individual self-serve account')], db_index=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=80, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('llm_daily_call_cap', models.PositiveIntegerField(default=500)),
                ('llm_monthly_call_cap', models.PositiveIntegerField(default=10000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'organizations',
                'ordering': ('pk',),
            },
        ),
    ]
