# Generated by Django 5.1.4 on 2026-07-03 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attempts', '0001_initial'),
        ('questions', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='questions.question'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.organization'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['learner', 'question'], name='attempts_learner_29f5ba_idx'),
        ),
    ]
