# Generated by Django 5.1.4 on 2026-07-03 03:59

import core.fields
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('EXAM', 'Exam preparation'), ('INTERVIEW', 'Interview preparation')], db_index=True, max_length=12)),
                ('topic_or_category', models.CharField(max_length=150)),
                ('difficulty', models.CharField(blank=True, choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], max_length=8, null=True)),
                ('category', models.CharField(blank=True, choices=[('BEHAVIORAL', 'Behavioral'), ('TECHNICAL', 'Technical')], max_length=12, null=True)),
                ('question_text', models.TextField()),
                ('reference_answer', models.TextField(blank=True)),
                ('embedding', core.fields.VectorField(blank=True, dimensions=1024, null=True)),
                ('source_chunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='materials.materialchunk')),
                ('source_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='materials.sourcematerial')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.organization')),
            ],
            options={
                'db_table': 'questions',
                'ordering': ('-pk',),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
