# Generated by Django 5.1.4 on 2026-07-03 03:59

import core.fields
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


def create_vector_extension(apps, schema_editor):
    """Enable pgvector before the embedding column is created.

    No-op on non-PostgreSQL backends (e.g. sqlite in tests), where the
    ``embedding`` column degrades to text (see core/fields.py). Requires the DB
    role to be allowed to CREATE EXTENSION; the pgvector/pgvector image permits it.
    """
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("CREATE EXTENSION IF NOT EXISTS vector")


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(create_vector_extension, migrations.RunPython.noop),
        migrations.CreateModel(
            name='SourceMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('EXAM', 'Exam preparation'), ('INTERVIEW', 'Interview preparation')], db_index=True, max_length=12)),
                ('subject_or_role', models.CharField(max_length=150)),
                ('topic', models.CharField(blank=True, max_length=150)),
                ('file', models.FileField(blank=True, null=True, upload_to='materials/')),
                ('source_text', models.TextField(blank=True)),
                ('ingestion_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('READY', 'Ready'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=12)),
                ('ingestion_error', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.organization')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_materials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'source_materials',
                'ordering': ('-pk',),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='MaterialChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chunk_index', models.PositiveIntegerField()),
                ('chunk_text', models.TextField()),
                ('embedding', core.fields.VectorField(blank=True, dimensions=1024, null=True)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.organization')),
                ('source_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='materials.sourcematerial')),
            ],
            options={
                'db_table': 'material_chunks',
                'ordering': ('source_material_id', 'chunk_index'),
                'constraints': [models.UniqueConstraint(fields=('source_material', 'chunk_index'), name='uniq_chunk_index_per_material')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
